name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: false  # Disable caching to avoid corrupt files

      # Step 3: Clear Micromamba Cache
      - name: Clear Micromamba Cache
        run: micromamba clean --all --yes

      # Step 4: Create environment and install dependencies
      - name: Create environment and install dependencies
        run: |
          micromamba create -n hairloom python=${{ matrix.python-version }} --yes
          micromamba install -n hairloom -y -c conda-forge -c bioconda pysam=0.22.1 pandas

      # Step 5: Install the package using pip
      - name: Install the package
        run: |
          micromamba run -n hairloom pip install .

      # Step 6: Run tests
      - name: Run tests
        run: |
          micromamba run -n hairloom pytest

