name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: false

      - name: Clear Micromamba Cache
        run: micromamba clean --all --yes

      - name: Create environment and install dependencies
        run: |
          micromamba create -n hairloom python=${{ matrix.python-version }} --yes
          micromamba install -n hairloom -y -c conda-forge pysam pandas

      - name: Install the package
        run: |
          micromamba run -n hairloom pip install .

      - name: Run tests
        run: |
          micromamba run -n hairloom pytest

