name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true

      # Step 3: Activate the environment and install dependencies
      - name: Activate and install dependencies
        run: |
          . ~/micromamba/etc/profile.d/micromamba.sh
          micromamba activate hairloom
          micromamba install -y -c conda-forge pysam pandas

      # Step 4: Install the package using pip
      - name: Install the package
        run: |
          . ~/micromamba/etc/profile.d/micromamba.sh
          micromamba activate hairloom
          pip install .

      # Step 5: Run tests
      - name: Run tests
        run: |
          . ~/micromamba/etc/profile.d/micromamba.sh
          micromamba activate hairloom
          pytest


