name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]  # Test on these Python versions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: false  # Disable caching to avoid using stale packages

      # Step 3: Create environment from environment.yml
      - name: Create the environment
        run: |
          micromamba env create -f environment.yml

      # Step 4: Install the package
      - name: Install package
        run: |
          micromamba run -n hairloom pip install .

      # Step 5: Activate environment and run tests
      - name: Run tests
        run: |
          micromamba run -n hairloom pytest

