name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"          # Specify your desired Python version
          environment-file: environment.yml  # Optional, if you use an environment.yml file
          activate-environment: hairloom  # Name of the environment to activate
          auto-activate-base: true
  
      # Step 3: Install dependencies using conda
      - name: Install prerequisites with conda
        run: |
          conda activate hairloom
          conda install -y -c conda-forge pysam
  
      # Step 4: Install the package using pip
      - name: Install the package
        run: |
          conda activate hairloom
          pip install -r requirements.txt
          pip install .
  
      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          conda activate hairloom
          pytest
