name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9"]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true

      # Step 3: Initialize Conda/Mamba
      - name: Initialize micromamba
        if: matrix.os == 'windows-latest'
        run: |
          micromamba shell init --shell bash --prefix $CONDA
          . $CONDA/etc/profile.d/conda.sh
          micromamba activate hairloom
        shell: bash

      - name: Initialize mamba on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          . ~/micromamba/etc/profile.d/micromamba.sh
          micromamba activate hairloom

      # Step 4: Install prerequisites using mamba
      - name: Install prerequisites
        run: |
          micromamba activate hairloom
          micromamba install -y -c conda-forge pysam pandas
        shell: bash

      # Step 5: Install the package using pip
      - name: Install the package
        run: |
          micromamba activate hairloom
          pip install .
        shell: bash

      # Step 6: Run tests
      - name: Run tests
        run: |
          micromamba activate hairloom
          pytest
        shell: bash


