name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9"]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true

      # Step 3: Create and activate the environment (Windows-specific fix)
      - name: Initialize and activate environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          micromamba create -n hairloom python=3.9 -y
          micromamba install -n hairloom -y -c conda-forge pysam pandas
          micromamba activate hairloom

      - name: Initialize and activate environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          . ~/micromamba/etc/profile.d/micromamba.sh
          micromamba activate hairloom
          micromamba install -n hairloom -y -c conda-forge pysam pandas

      # Step 4: Install the package using pip
      - name: Install the package
        run: |
          micromamba activate hairloom
          pip install .

      # Step 5: Run tests
      - name: Run tests
        run: |
          micromamba activate hairloom
          pytest

