name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9"]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Minimamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      # Step 3: Install dependencies using mamba
      - name: Install prerequisites with mamba
        run: |
          mamba activate hairloom
          mamba install -y -c mamba-forge pysam
  
      # Step 4: Install the package using pip
      - name: Install the package
        run: |
          mamba init
          mamba activate hairloom
          pip install -r requirements.txt
          pip install .
  
      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          mamba init
          mamba activate hairloom
          pytest
