name: Installation Integrity Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Micromamba
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true

      # Step 3: Install additional dependencies
      - name: Install dependencies
        run: |
          micromamba install -n hairloom -y -c conda-forge pysam pandas

      # Step 4: Install the package using pip
      - name: Install the package
        run: |
          micromamba run -n hairloom pip install .

      # Step 5: Run tests
      - name: Run tests
        run: |
          micromamba run -n hairloom pytest

